### PR TITLE
Fm6126 init

### PR DESCRIPTION
**Pull request by esden**
Added init sequence for the LED panels that use the FM6126 and similar chips.

### CODE REVIEW

**Comment by kbob** [comment]
The variable `led_driver.state` was one-hot in each implementation.  You modified it to be sometimes one-hot.  It seems like either one-hot or binary encoded would be best, not a hybrid of the two.

Is there something I'm missing?

Thanks.

Update: I compiled the `delay` demo with both a true one-hot and a binary encoded state.  The one-hot version has timing of 46.33 MHz, and the binary encoded version hits 51.80 MHz.  So at this point I favor the binary encoded version.

```
    localparam SH        = 4;
    localparam S_START   = 4'd0;
    localparam S_R1      = 4'd1;
    localparam S_R1E     = 4'd2;
    localparam S_R2      = 4'd3;
    localparam S_R2E     = 4'd4;
    localparam S_SDELAY  = 4'd5;
    localparam S_SHIFT0  = 4'd6;
    localparam S_SHIFT   = 4'd7;
    localparam S_SHIFTN  = 4'd8;
    localparam S_BLANK   = 4'd9;
    localparam S_UNBLANK = 4'd10;
    // ...
    reg [SH:0] state;
```

**Comment by esden** [comment]
Ok I think I made the changes you are talking about. Let me know if I missed something. :)

**Comment by kbob** [comment]
Merged.  Thank you!

**Comment by dado1973** [comment]
Hello this is my first post. I am seekeing for informations about FM6126 init sequence: I don't need any source code, but only the timing diagram and any trick not mentioned on the datasheet. 
Some time ago I had the same problem with Sumacro's drivers and  managed to get in touch with their engineers, that gave me support sending me all the needed infos. In this case I was unable to do the same thing with Fuman's engineers.
Anyone can help me ? Thanks in advance.

**Comment by kbob** [comment]
I think @esden reverse engineered this.  I don't think he got any information from the manufacturer.

**Pull request merged**
